### ISSUE TITLE
Day 2

### ISSUE THREAD

**Issue by kushagra414** [kushagra414/100-Days-of-Code#16]
#### Tasks
**DSA :**
> Data Structure(Compulsory)
- [x] [Finding middle element in a linked list](https://practice.geeksforgeeks.org/problems/finding-middle-element-in-a-linked-list/1)
- [x] [Reverse a linked list](https://practice.geeksforgeeks.org/problems/reverse-a-linked-list/1)
- [x] [Detect Loop in linked list](https://practice.geeksforgeeks.org/problems/detect-loop-in-linked-list/1)
> Algorithms(Optional)
- [x] [Sort an array of 0s, 1s and 2s](https://practice.geeksforgeeks.org/problems/sort-an-array-of-0s-1s-and-2s/0)
- [x] [Chocolate Distribution Problem](https://practice.geeksforgeeks.org/problems/chocolate-distribution-problem/0)
> GSOC
- [x] Work on some issues and try to fix them.
