### ISSUE TITLE
Day 3

### ISSUE THREAD

**Issue by kushagra414** [kushagra414/100-Days-of-Code#28]
#### Tasks
**DSA :**
> Data Structure(Compulsory)
- [x] [Immediate Smaller Element](https://practice.geeksforgeeks.org/problems/immediate-smaller-element/0)
- [x] [Level order traversal in spiral form](https://practice.geeksforgeeks.org/problems/level-order-traversal-in-spiral-form/1)
- [x] [Queue using two Stacks](https://practice.geeksforgeeks.org/problems/queue-using-two-stacks/1)
> Algorithms(Optional)
- [x] [Sort a stack](https://practice.geeksforgeeks.org/problems/sort-a-stack/1)
- [x] [Recursively remove all adjacent duplicates](https://practice.geeksforgeeks.org/problems/recursively-remove-all-adjacent-duplicates/0)
> GSOC
- [ ] Work on some issues and try to fix them.

**Comment by kushagra414** [comment]
f319128bd9386e8e4e3d72f262562c7b67fbcac5
