### ISSUE TITLE
Day 4

### ISSUE THREAD

**Issue by kushagra414** [kushagra414/100-Days-of-Code#35]
#### Tasks
**DSA :**
> Data Structure(Compulsory)
- [x] [Implement Queue using array](https://practice.geeksforgeeks.org/problems/implement-queue-using-array/1)
- [x] [Valid Substring](https://practice.geeksforgeeks.org/problems/valid-substring/0)
- [x] [Reverse First K elements of Queue](https://practice.geeksforgeeks.org/problems/reverse-first-k-elements-of-queue/1)
> Algorithms(Optional)
- [x] [Activity Selection](https://practice.geeksforgeeks.org/problems/activity-selection/0)
- [x] [Max length chain](https://practice.geeksforgeeks.org/problems/max-length-chain/1)
> GSOC
- [x] Work on some issues and try to fix them.
