### ISSUE TITLE
Day 6

### ISSUE THREAD

**Issue by kushagra414** [kushagra414/100-Days-of-Code#43]
#### Tasks
**DSA :**
> Data Structure(Compulsory)
- [x] [Minimum element in BST](https://practice.geeksforgeeks.org/problems/minimum-element-in-bst/1)
- [ ] [Inorder Successor in BST](https://practice.geeksforgeeks.org/problems/inorder-successor-in-bst/1)
- [x] [Array to BST](https://practice.geeksforgeeks.org/problems/array-to-bst/0)
- [x] [Insert a node in a BST](https://practice.geeksforgeeks.org/problems/insert-a-node-in-a-bst/1)
> Algorithms(Optional)
- [x] [Primes sum](https://practice.geeksforgeeks.org/problems/primes-sum/0)
- [ ] [Largest prime factor](https://practice.geeksforgeeks.org/problems/largest-prime-factor/0)
> GSOC
- [ ] Work on some issues and try to fix them.
