### ISSUE TITLE
Day 8

### ISSUE THREAD

**Issue by kushagra414** [kushagra414/100-Days-of-Code#52]
#### Tasks
**DSA :**
> Data Structure(Compulsory)
- [x] [Spirally traversing a matrix](https://practice.geeksforgeeks.org/problems/spirally-traversing-a-matrix/0)
- [x] [Search in a matrix](https://practice.geeksforgeeks.org/problems/search-in-a-matrix/0)
- [x] [Flood fill Algorithm](https://practice.geeksforgeeks.org/problems/flood-fill-algorithm/0)
> GSOC
- [ ] Work on some issues and try to fix them.
