### ISSUE TITLE
Day 9

### ISSUE THREAD

**Issue by kushagra414** [kushagra414/100-Days-of-Code#54]
#### Tasks
**DSA :**
> Data Structure(Compulsory)
- [x] [Equilibrium point](https://practice.geeksforgeeks.org/problems/equilibrium-point/0)
- [x] [Maximum Index](https://practice.geeksforgeeks.org/problems/maximum-index/0)
- [x] [Inversion of array](https://practice.geeksforgeeks.org/problems/inversion-of-array/0)
> GSOC
- [ ] Work on some issues and try to fix them.
