### ISSUE TITLE
Day 10

### ISSUE THREAD

**Issue by kushagra414** [kushagra414/100-Days-of-Code#57]
#### Tasks
**DSA :**
> Data Structure(Compulsory)
- [x] [Check if Linked List is Palindrome](https://practice.geeksforgeeks.org/problems/check-if-linked-list-is-pallindrome/1)
- [x] [Nth node from end of linked list](https://practice.geeksforgeeks.org/problems/nth-node-from-end-of-linked-list/1)
- [x] [Remove loop in Linked List](https://practice.geeksforgeeks.org/problems/remove-loop-in-linked-list/1)
> GSOC
- [ ] Work on some issues and try to fix them.
