### ISSUE TITLE
Day 11

### ISSUE THREAD

**Issue by kushagra414** [kushagra414/100-Days-of-Code#59]
#### Tasks
**DSA :**
> Data Structure(Compulsory)
- [x] [Parenthesis Checker](https://practice.geeksforgeeks.org/problems/parenthesis-checker/0)
- [x] [Next larger element](https://practice.geeksforgeeks.org/problems/next-larger-element/0)
- [x] [Get minimum element from stack](https://practice.geeksforgeeks.org/problems/get-minimum-element-from-stack/1)
> GSOC
- [ ] Work on some issues and try to fix them.
