### ISSUE TITLE
Day 12

### ISSUE THREAD

**Issue by kushagra414** [kushagra414/100-Days-of-Code#64]
#### Tasks
**DSA :**
> Data Structure(Compulsory)
- [ ] [LRU Cache](https://practice.geeksforgeeks.org/problems/lru-cache/1)
- [ ] [Stack using two queues](https://practice.geeksforgeeks.org/problems/stack-using-two-queues/1)
- [ ] [Maximum of all subarrays of size k](https://practice.geeksforgeeks.org/problems/maximum-of-all-subarrays-of-size-k/0)
- [ ] [Circular tour](https://practice.geeksforgeeks.org/problems/circular-tour/1)
> GSOC
- [ ] Work on some issues and try to fix them.
