### ISSUE TITLE
Day 13

### ISSUE THREAD

**Issue by kushagra414** [kushagra414/100-Days-of-Code#66]
#### Tasks
**DSA :**
> Data Structure(Compulsory)
- [x] [Sum Tree](https://practice.geeksforgeeks.org/problems/sum-tree/1)
- [ ] [Check for BST](https://practice.geeksforgeeks.org/problems/check-for-bst/1)
- [x] [Root to leaf path sum](https://practice.geeksforgeeks.org/problems/root-to-leaf-path-sum/1)
> GSOC
- [ ] Work on some issues and try to fix them.

**Comment by kushagra414** [comment]
d80ab00945ec66bd893c8d0775e66f1c58dcb920
